SET
  ANSI_PADDING ON
GO
  /****** Object:  Index [IX_WORKORDERUSERSTATUS_AUFNRFK_UDATE]    Script Date: 06.11.2018 15:21:31 ******/
  CREATE NONCLUSTERED INDEX [IX_WORKORDERUSERSTATUS_AUFNRFK_UDATE] ON [dbo].[WorkOrderUserStatus] (
    [Aufnr_fk] ASC,
	[Udate] ASC
  ) WITH (
    STATISTICS_NORECOMPUTE = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF
  ) ON [PRIMARY]
GO