/****** Object:  Table [safran].[ACT_IMPACT]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[ACT_IMPACT](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[AN_SEQ] [int] NOT NULL,
	[NET_ID] [int] NOT NULL,
	[SET_NR] [int] NOT NULL,
	[DU] [int] NULL,
	[DUR_FMT] [int] NULL,
	[ACT_EXIST] [int] NULL,
	[ESA] [datetime2](7) NULL,
	[ES] [datetime2](7) NULL,
	[EF] [datetime2](7) NULL,
	[LS] [datetime2](7) NULL,
	[LF] [datetime2](7) NULL,
	[TF] [int] NULL,
	[FF] [int] NULL,
	[WPN] [int] NULL,
 CONSTRAINT [PK_ACT_IMPACT_NET_ID_AN_SEQ_SET_NR] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[NET_ID] ASC,
	[AN_SEQ] ASC,
	[SET_NR] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[ACT_RISK]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[ACT_RISK](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[AN_SEQ] [int] NOT NULL,
	[NET_ID] [int] NOT NULL,
	[MAXDU] [int] NULL,
	[MINDU] [int] NULL,
	[DEFDU] [int] NOT NULL,
	[DISTRIBUTE] [int] NOT NULL,
	[NOTES] [nvarchar](2000) NULL,
	[CRIT_IX] [float] NULL,
	[MEANDU] [int] NULL,
	[MEAN_START] [datetime2](7) NULL,
	[MEAN_FIN] [datetime2](7) NULL,
	[EES] [datetime2](7) NULL,
	[LES] [datetime2](7) NULL,
	[EEF] [datetime2](7) NULL,
	[LEF] [datetime2](7) NULL,
	[TFMAX] [int] NULL,
	[TFMIN] [int] NULL,
	[DU_SENS] [float] NULL,
	[SCH_SENS] [float] NULL,
	[MEAN_COST] [float] NULL,
	[STD_DEV_DUR] [float] NULL,
	[STD_DEV_COST] [float] NULL,
 CONSTRAINT [PK_ACT_RISK_NET_ID_AN_SEQ] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[NET_ID] ASC,
	[AN_SEQ] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran_staging].[ACTIVITIES]    Script Date: 28.10.2019 16:31:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[ACTIVITIES](
	[META_OraRowscn] [bigint] NULL,
	[META_SourceDatabase] int NOT NULL,
	[SEQ] [int] NOT NULL,
	[AN] [nvarchar](50) NULL,
	[DU] [int] NULL,
	[PC] [float] NULL,
	[RDU] [int] NULL,
	[WPN] [int] NULL,
	[TSE] [datetime2](7) NULL,
	[TSL] [datetime2](7) NULL,
	[TCE] [datetime2](7) NULL,
	[TCL] [datetime2](7) NULL,
	[ACS] [datetime2](7) NULL,
	[ACF] [datetime2](7) NULL,
	[ES] [datetime2](7) NULL,
	[EF] [datetime2](7) NULL,
	[LS] [datetime2](7) NULL,
	[LF] [datetime2](7) NULL,
	[TF] [int] NULL,
	[FF] [int] NULL,
	[DES] [nvarchar](255) NULL,
	[SUBNET_ID] [int] NULL,
	[NET_ID] [int] NOT NULL,
	[R1] [int] NULL,
	[R2] [int] NULL,
	[R3] [int] NULL,
	[R4] [int] NULL,
	[R5] [int] NULL,
	[R6] [int] NULL,
	[R7] [int] NULL,
	[R8] [int] NULL,
	[R9] [int] NULL,
	[R10] [int] NULL,
	[R11] [int] NULL,
	[R12] [int] NULL,
	[R13] [int] NULL,
	[R14] [int] NULL,
	[R15] [int] NULL,
	[R16] [int] NULL,
	[R17] [int] NULL,
	[R18] [int] NULL,
	[R19] [int] NULL,
	[R20] [int] NULL,
	[R21] [int] NULL,
	[R22] [int] NULL,
	[R23] [int] NULL,
	[R24] [int] NULL,
	[R25] [int] NULL,
	[R26] [int] NULL,
	[R27] [int] NULL,
	[R28] [int] NULL,
	[R29] [int] NULL,
	[R30] [int] NULL,
	[D1] [datetime2](7) NULL,
	[D2] [datetime2](7) NULL,
	[D3] [datetime2](7) NULL,
	[D4] [datetime2](7) NULL,
	[D5] [datetime2](7) NULL,
	[D6] [datetime2](7) NULL,
	[D7] [datetime2](7) NULL,
	[D8] [datetime2](7) NULL,
	[D9] [datetime2](7) NULL,
	[D10] [datetime2](7) NULL,
	[D11] [datetime2](7) NULL,
	[D12] [datetime2](7) NULL,
	[D13] [datetime2](7) NULL,
	[D14] [datetime2](7) NULL,
	[D15] [datetime2](7) NULL,
	[D16] [datetime2](7) NULL,
	[D17] [datetime2](7) NULL,
	[D18] [datetime2](7) NULL,
	[D19] [datetime2](7) NULL,
	[D20] [datetime2](7) NULL,
	[N1] [float] NULL,
	[N2] [float] NULL,
	[N3] [float] NULL,
	[N4] [float] NULL,
	[N5] [float] NULL,
	[N6] [float] NULL,
	[N7] [float] NULL,
	[N8] [float] NULL,
	[N9] [float] NULL,
	[N10] [float] NULL,
	[N11] [float] NULL,
	[N12] [float] NULL,
	[N13] [float] NULL,
	[N14] [float] NULL,
	[N15] [float] NULL,
	[N16] [float] NULL,
	[N17] [float] NULL,
	[N18] [float] NULL,
	[N19] [float] NULL,
	[N20] [float] NULL,
	[L1] [int] NULL,
	[L2] [int] NULL,
	[L3] [int] NULL,
	[L4] [int] NULL,
	[L5] [int] NULL,
	[L6] [int] NULL,
	[L7] [int] NULL,
	[L8] [int] NULL,
	[L9] [int] NULL,
	[L10] [int] NULL,
	[L11] [int] NULL,
	[L12] [int] NULL,
	[L13] [int] NULL,
	[L14] [int] NULL,
	[L15] [int] NULL,
	[L16] [int] NULL,
	[L17] [int] NULL,
	[L18] [int] NULL,
	[L19] [int] NULL,
	[L20] [int] NULL,
	[ON_TARGET] [int] NULL,
	[JOBFLAG] [int] NULL,
	[CURRENT_PROGRESS] [float] NULL,
	[FRONTLINE_DATE] [datetime2](7) NULL,
	[CANCELLED] [datetime2](7) NULL,
	[REMARKS] [varchar](max) NULL,
	[ORIGINAL_QTY] [float] NULL,
	[APPROVED_VO_QTY] [float] NULL,
	[ESTIMATED_VO_QTY] [float] NULL,
	[SUBCONTR_VO_QTY] [float] NULL,
	[INTERNAL_VO_QTY] [float] NULL,
	[JOBPACK_EST_QTY] [float] NULL,
	[EXPENDED_QTY] [float] NULL,
	[ESA] [datetime2](7) NULL,
	[CURRENT_AS] [datetime2](7) NULL,
	[CURRENT_AF] [datetime2](7) NULL,
	[CURRENT_PLANNED_PROG] [float] NULL,
	[BASE_PLANNED_PROG] [float] NULL,
	[OES] [datetime2](7) NULL,
	[OEF] [datetime2](7) NULL,
	[OLS] [datetime2](7) NULL,
	[OLF] [datetime2](7) NULL,
	[BES] [datetime2](7) NULL,
	[BESA] [datetime2](7) NULL,
	[BEF] [datetime2](7) NULL,
	[BLS] [datetime2](7) NULL,
	[BLF] [datetime2](7) NULL,
	[CES] [datetime2](7) NULL,
	[CEF] [datetime2](7) NULL,
	[CLS] [datetime2](7) NULL,
	[CLF] [datetime2](7) NULL,
	[ORIGINAL_QTY1] [float] NULL,
	[CSH] [float] NULL,
	[RSH] [float] NULL,
	[TSH] [float] NULL,
	[CURR_FRONTLINE_DATE] [datetime2](7) NULL,
	[ESS] [datetime2](7) NULL,
	[EFS] [datetime2](7) NULL,
	[TFS] [int] NULL,
	[FFS] [int] NULL,
	[HAMMOCK] [int] NULL,
	[ANALYSE_OPT] [int] NULL,
	[FSD] [datetime2](7) NULL,
	[FFD] [datetime2](7) NULL,
	[MANUAL_PROG_FLAG] [int] NULL,
	[CURRENT_PC] [float] NULL,
	[RDUA] [int] NULL,
	[CESA] [datetime2](7) NULL,
	[CTF] [int] NULL,
	[CFF] [int] NULL,
	[LOOS] [int] NULL,
	[COOS] [int] NULL,
	[OUT_OF_SYNC] [int] NULL,
	[FCDU] [int] NULL,
	[FCESA] [datetime2](7) NULL,
	[FCEF] [datetime2](7) NULL,
	[RESA] [datetime2](7) NULL,
	[RES] [datetime2](7) NULL,
	[REF] [datetime2](7) NULL,
	[RLS] [datetime2](7) NULL,
	[RLF] [datetime2](7) NULL,
	[REVISED_PLANNED_PROG] [float] NULL,
	[REV_FRONTLINE_DATE] [datetime2](7) NULL,
	[FCQTY] [float] NULL,
	[DUR_FMT] [int] NULL,
	[O1] [int] NULL,
	[O2] [int] NULL,
	[O3] [int] NULL,
	[O4] [int] NULL,
	[O5] [int] NULL,
	[O6] [int] NULL,
	[O7] [int] NULL,
	[O8] [int] NULL,
	[O9] [int] NULL,
	[O10] [int] NULL,
	[O11] [int] NULL,
	[O12] [int] NULL,
	[O13] [int] NULL,
	[O14] [int] NULL,
	[O15] [int] NULL,
	[O16] [int] NULL,
	[O17] [int] NULL,
	[O18] [int] NULL,
	[O19] [int] NULL,
	[O20] [int] NULL,
	[O21] [int] NULL,
	[O22] [int] NULL,
	[O23] [int] NULL,
	[O24] [int] NULL,
	[O25] [int] NULL,
	[O26] [int] NULL,
	[O27] [int] NULL,
	[O28] [int] NULL,
	[O29] [int] NULL,
	[O30] [int] NULL,
	[ROW_NO] [int] NULL,
	[OUTLINE_LEVEL] [int] NULL,
	[LINK_SUMMARY] [int] NULL,
	[CPC] [float] NULL,
	[REV_SCOPE] [float] NULL,
	[U1] [nvarchar](10) NULL,
	[U2] [nvarchar](10) NULL,
	[U3] [nvarchar](10) NULL,
	[U4] [nvarchar](10) NULL,
	[U5] [nvarchar](10) NULL,
	[U6] [nvarchar](10) NULL,
	[U7] [nvarchar](10) NULL,
	[U8] [nvarchar](10) NULL,
	[U9] [nvarchar](10) NULL,
	[U10] [nvarchar](10) NULL,
	[EVM_METHOD] [nvarchar](2) NULL,
	[EVM_PARM] [nvarchar](100) NULL,
	[MIN_DUR] [int] NULL,
	[ACT_EXI] [int] NULL,
	[ACT_FIT] [int] NULL,
	[ALAP] [int] NULL,
	[ACT_TYPE] [int] NULL,
	[LOOK_AHEAD] [int] NULL,
	[R31] [int] NULL,
	[R32] [int] NULL,
	[R33] [int] NULL,
	[R34] [int] NULL,
	[R35] [int] NULL,
	[R36] [int] NULL,
	[R37] [int] NULL,
	[R38] [int] NULL,
	[R39] [int] NULL,
	[R40] [int] NULL,
	[R41] [int] NULL,
	[R42] [int] NULL,
	[R43] [int] NULL,
	[R44] [int] NULL,
	[R45] [int] NULL,
	[R46] [int] NULL,
	[R47] [int] NULL,
	[R48] [int] NULL,
	[R49] [int] NULL,
	[R50] [int] NULL,
	[R51] [int] NULL,
	[R52] [int] NULL,
	[R53] [int] NULL,
	[R54] [int] NULL,
	[R55] [int] NULL,
	[R56] [int] NULL,
	[R57] [int] NULL,
	[R58] [int] NULL,
	[R59] [int] NULL,
	[R60] [int] NULL,
	[D21] [datetime2](7) NULL,
	[D22] [datetime2](7) NULL,
	[D23] [datetime2](7) NULL,
	[D24] [datetime2](7) NULL,
	[D25] [datetime2](7) NULL,
	[D26] [datetime2](7) NULL,
	[D27] [datetime2](7) NULL,
	[D28] [datetime2](7) NULL,
	[D29] [datetime2](7) NULL,
	[D30] [datetime2](7) NULL,
	[D31] [datetime2](7) NULL,
	[D32] [datetime2](7) NULL,
	[D33] [datetime2](7) NULL,
	[D34] [datetime2](7) NULL,
	[D35] [datetime2](7) NULL,
	[D36] [datetime2](7) NULL,
	[D37] [datetime2](7) NULL,
	[D38] [datetime2](7) NULL,
	[D39] [datetime2](7) NULL,
	[D40] [datetime2](7) NULL,
	[CURRENT_RDU] [float] NULL,
	[ESAS] [datetime2](7) NULL,
 CONSTRAINT [PK_ACTIVITIES] PRIMARY KEY CLUSTERED 
(
	[META_SourceDatabase] ASC,
	[NET_ID] ASC,
	[SEQ] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[ACTIVITIES_TEMP]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[ACTIVITIES_TEMP](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[USER_ID] [nvarchar](15) NULL,
	[SEQ_ORIG] [float] NULL,
	[SEQ] [float] NULL,
	[AN] [nvarchar](255) NULL,
	[DU] [float] NULL,
	[PC] [float] NULL,
	[RDU] [float] NULL,
	[WPN] [float] NULL,
	[TSE] [datetime2](7) NULL,
	[TSL] [datetime2](7) NULL,
	[TCE] [datetime2](7) NULL,
	[TCL] [datetime2](7) NULL,
	[ACS] [datetime2](7) NULL,
	[ACF] [datetime2](7) NULL,
	[ES] [datetime2](7) NULL,
	[LS] [datetime2](7) NULL,
	[EF] [datetime2](7) NULL,
	[LF] [datetime2](7) NULL,
	[TF] [float] NULL,
	[FF] [float] NULL,
	[DES] [nvarchar](255) NULL,
	[SUBNET_ID] [float] NULL,
	[NET_ID] [float] NULL,
	[F1] [nvarchar](50) NULL,
	[F2] [nvarchar](50) NULL,
	[F3] [nvarchar](50) NULL,
	[F4] [nvarchar](50) NULL,
	[F5] [nvarchar](50) NULL,
	[F6] [nvarchar](50) NULL,
	[F7] [nvarchar](50) NULL,
	[F8] [nvarchar](50) NULL,
	[F9] [nvarchar](50) NULL,
	[F10] [nvarchar](50) NULL,
	[F11] [nvarchar](20) NULL,
	[F12] [nvarchar](20) NULL,
	[F13] [nvarchar](20) NULL,
	[F14] [nvarchar](20) NULL,
	[F15] [nvarchar](20) NULL,
	[F16] [nvarchar](20) NULL,
	[F17] [nvarchar](20) NULL,
	[F18] [nvarchar](20) NULL,
	[F19] [nvarchar](20) NULL,
	[F20] [nvarchar](20) NULL,
	[R1] [float] NULL,
	[R2] [float] NULL,
	[R3] [float] NULL,
	[R4] [float] NULL,
	[R5] [float] NULL,
	[R6] [float] NULL,
	[R7] [float] NULL,
	[R8] [float] NULL,
	[R9] [float] NULL,
	[R10] [float] NULL,
	[R11] [float] NULL,
	[R12] [float] NULL,
	[R13] [float] NULL,
	[R14] [float] NULL,
	[R15] [float] NULL,
	[R16] [float] NULL,
	[R17] [float] NULL,
	[R18] [float] NULL,
	[R19] [float] NULL,
	[R20] [float] NULL,
	[R21] [float] NULL,
	[R22] [float] NULL,
	[R23] [float] NULL,
	[R24] [float] NULL,
	[R25] [float] NULL,
	[R26] [float] NULL,
	[R27] [float] NULL,
	[R28] [float] NULL,
	[R29] [float] NULL,
	[R30] [float] NULL,
	[D1] [datetime2](7) NULL,
	[D2] [datetime2](7) NULL,
	[D3] [datetime2](7) NULL,
	[D4] [datetime2](7) NULL,
	[D5] [datetime2](7) NULL,
	[D6] [datetime2](7) NULL,
	[D7] [datetime2](7) NULL,
	[D8] [datetime2](7) NULL,
	[D9] [datetime2](7) NULL,
	[D10] [datetime2](7) NULL,
	[D11] [datetime2](7) NULL,
	[D12] [datetime2](7) NULL,
	[D13] [datetime2](7) NULL,
	[D14] [datetime2](7) NULL,
	[D15] [datetime2](7) NULL,
	[D16] [datetime2](7) NULL,
	[D17] [datetime2](7) NULL,
	[D18] [datetime2](7) NULL,
	[D19] [datetime2](7) NULL,
	[D20] [datetime2](7) NULL,
	[N1] [float] NULL,
	[N2] [float] NULL,
	[N3] [float] NULL,
	[N4] [float] NULL,
	[N5] [float] NULL,
	[N6] [float] NULL,
	[N7] [float] NULL,
	[N8] [float] NULL,
	[N9] [float] NULL,
	[N10] [float] NULL,
	[I1] [float] NULL,
	[I2] [float] NULL,
	[I3] [float] NULL,
	[I4] [float] NULL,
	[I5] [float] NULL,
	[I6] [float] NULL,
	[I7] [float] NULL,
	[I8] [float] NULL,
	[I9] [float] NULL,
	[I10] [float] NULL,
	[L1] [int] NULL,
	[L2] [int] NULL,
	[L3] [int] NULL,
	[L4] [int] NULL,
	[L5] [int] NULL,
	[L6] [int] NULL,
	[L7] [int] NULL,
	[L8] [int] NULL,
	[L9] [int] NULL,
	[L10] [int] NULL,
	[L11] [int] NULL,
	[L12] [int] NULL,
	[L13] [int] NULL,
	[L14] [int] NULL,
	[L15] [int] NULL,
	[L16] [int] NULL,
	[L17] [int] NULL,
	[L18] [int] NULL,
	[L19] [int] NULL,
	[L20] [int] NULL,
	[ON_TARGET] [int] NULL,
	[JOBFLAG] [int] NULL,
	[CURRENT_PROGRESS] [float] NULL,
	[FRONTLINE_DATE] [datetime2](7) NULL,
	[CANCELLED] [datetime2](7) NULL,
	[REMARKS] [varchar](max) NULL,
	[ORIGINAL_QTY] [float] NULL,
	[BASELINE_QTY] [float] NULL,
	[APPROVED_VO_QTY] [float] NULL,
	[ESTIMATED_VO_QTY] [float] NULL,
	[SUBCONTR_VO_QTY] [float] NULL,
	[INTERNAL_VO_QTY] [float] NULL,
	[JOBPACK_EST_QTY] [float] NULL,
	[EXPENDED_QTY] [float] NULL,
	[ESA] [datetime2](7) NULL,
	[TEMP_SYSTEM_CODE] [nvarchar](20) NULL,
	[CURRENT_AS] [datetime2](7) NULL,
	[CURRENT_AF] [datetime2](7) NULL,
	[CURRENT_PLANNED_PROG] [float] NULL,
	[BASE_PLANNED_PROG] [float] NULL,
	[TEMP_SYSTEM_DEC1] [float] NULL,
	[TEMP_SYSTEM_DEC2] [float] NULL,
	[OES] [datetime2](7) NULL,
	[OEF] [datetime2](7) NULL,
	[OLS] [datetime2](7) NULL,
	[OLF] [datetime2](7) NULL,
	[BES] [datetime2](7) NULL,
	[BESA] [datetime2](7) NULL,
	[BEF] [datetime2](7) NULL,
	[BLS] [datetime2](7) NULL,
	[BLF] [datetime2](7) NULL,
	[CES] [datetime2](7) NULL,
	[CESA] [datetime2](7) NULL,
	[CEF] [datetime2](7) NULL,
	[CLS] [datetime2](7) NULL,
	[CLF] [datetime2](7) NULL,
	[ORIGINAL_QTY1] [float] NULL,
	[BASELINE_QTY1] [float] NULL,
	[CSH] [float] NULL,
	[RSH] [float] NULL,
	[TSH] [float] NULL,
	[CURR_FRONTLINE_DATE] [datetime2](7) NULL,
	[ESS] [datetime2](7) NULL,
	[EFS] [datetime2](7) NULL,
	[TFS] [float] NULL,
	[FFS] [float] NULL,
	[HAMMOCK] [int] NULL,
	[ANALYSE_OPT] [float] NULL,
	[FSD] [datetime2](7) NULL,
	[FFD] [datetime2](7) NULL,
	[INDEX_COL_UNI] [nvarchar](240) NULL,
	[RESA] [datetime2](7) NULL,
	[RES] [datetime2](7) NULL,
	[REF] [datetime2](7) NULL,
	[RLS] [datetime2](7) NULL,
	[RLF] [datetime2](7) NULL,
	[REVISED_PLANNED_PROG] [float] NULL,
	[REV_FRONTLINE_DATE] [datetime2](7) NULL,
	[R31] [int] NULL,
	[R32] [int] NULL,
	[R33] [int] NULL,
	[R34] [int] NULL,
	[R35] [int] NULL,
	[R36] [int] NULL,
	[R37] [int] NULL,
	[R38] [int] NULL,
	[R39] [int] NULL,
	[R40] [int] NULL,
	[R41] [int] NULL,
	[R42] [int] NULL,
	[R43] [int] NULL,
	[R44] [int] NULL,
	[R45] [int] NULL,
	[R46] [int] NULL,
	[R47] [int] NULL,
	[R48] [int] NULL,
	[R49] [int] NULL,
	[R50] [int] NULL,
	[R51] [int] NULL,
	[R52] [int] NULL,
	[R53] [int] NULL,
	[R54] [int] NULL,
	[R55] [int] NULL,
	[R56] [int] NULL,
	[R57] [int] NULL,
	[R58] [int] NULL,
	[R59] [int] NULL,
	[R60] [int] NULL,
	[F21] [nvarchar](50) NULL,
	[F22] [nvarchar](50) NULL,
	[F23] [nvarchar](50) NULL,
	[F24] [nvarchar](50) NULL,
	[F25] [nvarchar](50) NULL,
	[F26] [nvarchar](50) NULL,
	[F27] [nvarchar](50) NULL,
	[F28] [nvarchar](50) NULL,
	[F29] [nvarchar](50) NULL,
	[F30] [nvarchar](50) NULL,
	[F31] [nvarchar](50) NULL,
	[F32] [nvarchar](50) NULL,
	[F33] [nvarchar](50) NULL,
	[F34] [nvarchar](50) NULL,
	[F35] [nvarchar](50) NULL,
	[F36] [nvarchar](50) NULL,
	[F37] [nvarchar](50) NULL,
	[F38] [nvarchar](50) NULL,
	[F39] [nvarchar](50) NULL,
	[F40] [nvarchar](50) NULL
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[ACTIVITY_BARS]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[ACTIVITY_BARS](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[AN_SEQ] [int] NOT NULL,
	[NET_ID] [int] NOT NULL,
	[STANDARD_ID] [int] NOT NULL,
	[DATE_FROM] [datetime2](7) NULL,
	[DATE_UNTIL] [datetime2](7) NULL,
	[EXTRA_TEXT] [nvarchar](255) NULL
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[ACTIVITY_HISTORY]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[ACTIVITY_HISTORY](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[NET_ID] [int] NOT NULL,
	[CUT_OFF_DATE] [datetime2](7) NOT NULL,
	[SEQ] [int] NOT NULL,
	[AN] [nvarchar](50) NULL,
	[DU] [int] NULL,
	[PC] [float] NULL,
	[RDU] [int] NULL,
	[WPN] [int] NULL,
	[TSE] [datetime2](7) NULL,
	[TSL] [datetime2](7) NULL,
	[TCE] [datetime2](7) NULL,
	[TCL] [datetime2](7) NULL,
	[ACS] [datetime2](7) NULL,
	[ACF] [datetime2](7) NULL,
	[ES] [datetime2](7) NULL,
	[ESA] [datetime2](7) NULL,
	[EF] [datetime2](7) NULL,
	[LS] [datetime2](7) NULL,
	[LF] [datetime2](7) NULL,
	[TF] [int] NULL,
	[FF] [int] NULL,
	[DES] [nvarchar](255) NULL,
	[F1] [nvarchar](255) NULL,
	[F2] [nvarchar](255) NULL,
	[F3] [nvarchar](255) NULL,
	[F4] [nvarchar](255) NULL,
	[F5] [nvarchar](255) NULL,
	[F6] [nvarchar](50) NULL,
	[F7] [nvarchar](50) NULL,
	[F8] [nvarchar](50) NULL,
	[F9] [nvarchar](50) NULL,
	[F10] [nvarchar](50) NULL,
	[F11] [nvarchar](50) NULL,
	[F12] [nvarchar](50) NULL,
	[F13] [nvarchar](50) NULL,
	[F14] [nvarchar](50) NULL,
	[F15] [nvarchar](50) NULL,
	[F16] [nvarchar](50) NULL,
	[F17] [nvarchar](50) NULL,
	[F18] [nvarchar](50) NULL,
	[F19] [nvarchar](50) NULL,
	[F20] [nvarchar](50) NULL,
	[R1] [int] NULL,
	[R2] [int] NULL,
	[R3] [int] NULL,
	[R4] [int] NULL,
	[R5] [int] NULL,
	[R6] [int] NULL,
	[R7] [int] NULL,
	[R8] [int] NULL,
	[R9] [int] NULL,
	[R10] [int] NULL,
	[R11] [int] NULL,
	[R12] [int] NULL,
	[R13] [int] NULL,
	[R14] [int] NULL,
	[R15] [int] NULL,
	[R16] [int] NULL,
	[R17] [int] NULL,
	[R18] [int] NULL,
	[R19] [int] NULL,
	[R20] [int] NULL,
	[R21] [int] NULL,
	[R22] [int] NULL,
	[R23] [int] NULL,
	[R24] [int] NULL,
	[R25] [int] NULL,
	[R26] [int] NULL,
	[R27] [int] NULL,
	[R28] [int] NULL,
	[R29] [int] NULL,
	[R30] [int] NULL,
	[D1] [datetime2](7) NULL,
	[D2] [datetime2](7) NULL,
	[D3] [datetime2](7) NULL,
	[D4] [datetime2](7) NULL,
	[D5] [datetime2](7) NULL,
	[D6] [datetime2](7) NULL,
	[D7] [datetime2](7) NULL,
	[D8] [datetime2](7) NULL,
	[D9] [datetime2](7) NULL,
	[D10] [datetime2](7) NULL,
	[D11] [datetime2](7) NULL,
	[D12] [datetime2](7) NULL,
	[D13] [datetime2](7) NULL,
	[D14] [datetime2](7) NULL,
	[D15] [datetime2](7) NULL,
	[D16] [datetime2](7) NULL,
	[D17] [datetime2](7) NULL,
	[D18] [datetime2](7) NULL,
	[D19] [datetime2](7) NULL,
	[D20] [datetime2](7) NULL,
	[N1] [float] NULL,
	[N2] [float] NULL,
	[N3] [float] NULL,
	[N4] [float] NULL,
	[N5] [float] NULL,
	[N6] [float] NULL,
	[N7] [float] NULL,
	[N8] [float] NULL,
	[N9] [float] NULL,
	[N10] [float] NULL,
	[I1] [int] NULL,
	[I2] [int] NULL,
	[I3] [int] NULL,
	[I4] [int] NULL,
	[I5] [int] NULL,
	[I6] [int] NULL,
	[I7] [int] NULL,
	[I8] [int] NULL,
	[I9] [int] NULL,
	[I10] [int] NULL,
	[L1] [int] NULL,
	[L2] [int] NULL,
	[L3] [int] NULL,
	[L4] [int] NULL,
	[L5] [int] NULL,
	[L6] [int] NULL,
	[L7] [int] NULL,
	[L8] [int] NULL,
	[L9] [int] NULL,
	[L10] [int] NULL,
	[L11] [int] NULL,
	[L12] [int] NULL,
	[L13] [int] NULL,
	[L14] [int] NULL,
	[L15] [int] NULL,
	[L16] [int] NULL,
	[L17] [int] NULL,
	[L18] [int] NULL,
	[L19] [int] NULL,
	[L20] [int] NULL,
	[ON_TARGET] [int] NULL,
	[JOBFLAG] [int] NULL,
	[CANCELLED] [datetime2](7) NULL,
	[CURRENT_AS] [datetime2](7) NULL,
	[CURRENT_AF] [datetime2](7) NULL,
	[CURRENT_PROGRESS] [float] NULL,
	[APPROVED_VO_QTY] [float] NULL,
	[ESTIMATED_VO_QTY] [float] NULL,
	[SUBCONTR_VO_QTY] [float] NULL,
	[INTERNAL_VO_QTY] [float] NULL,
	[CTF] [int] NULL,
	[CURRENT_PLANNED_PROG] [float] NULL,
	[BASE_PLANNED_PROG] [float] NULL,
	[OES] [datetime2](7) NULL,
	[OEF] [datetime2](7) NULL,
	[OLS] [datetime2](7) NULL,
	[OLF] [datetime2](7) NULL,
	[BES] [datetime2](7) NULL,
	[BESA] [datetime2](7) NULL,
	[BEF] [datetime2](7) NULL,
	[BLS] [datetime2](7) NULL,
	[BLF] [datetime2](7) NULL,
	[CES] [datetime2](7) NULL,
	[CEF] [datetime2](7) NULL,
	[CLS] [datetime2](7) NULL,
	[CLF] [datetime2](7) NULL,
	[CSH] [float] NULL,
	[RSH] [float] NULL,
	[TSH] [float] NULL,
	[CURR_FRONTLINE_DATE] [datetime2](7) NULL,
	[MANUAL_PROG_FLAG] [int] NULL,
	[CURRENT_PC] [float] NULL,
	[CESA] [datetime2](7) NULL,
	[SUBNET_ID] [int] NULL,
	[RESA] [datetime2](7) NULL,
	[RES] [datetime2](7) NULL,
	[REF] [datetime2](7) NULL,
	[RLS] [datetime2](7) NULL,
	[RLF] [datetime2](7) NULL,
	[REVISED_PLANNED_PROG] [float] NULL,
	[REV_FRONTLINE_DATE] [datetime2](7) NULL,
	[CPC] [float] NULL,
	[REV_SCOPE] [float] NULL,
	[U1] [nvarchar](10) NULL,
	[U2] [nvarchar](10) NULL,
	[U3] [nvarchar](10) NULL,
	[U4] [nvarchar](10) NULL,
	[U5] [nvarchar](10) NULL,
	[U6] [nvarchar](10) NULL,
	[U7] [nvarchar](10) NULL,
	[U8] [nvarchar](10) NULL,
	[U9] [nvarchar](10) NULL,
	[U10] [nvarchar](10) NULL,
	[O1] [int] NULL,
	[O2] [int] NULL,
	[O3] [int] NULL,
	[O4] [int] NULL,
	[O5] [int] NULL,
	[O6] [int] NULL,
	[O7] [int] NULL,
	[O8] [int] NULL,
	[O9] [int] NULL,
	[O10] [int] NULL,
	[O11] [int] NULL,
	[O12] [int] NULL,
	[O13] [int] NULL,
	[O14] [int] NULL,
	[O15] [int] NULL,
	[O16] [int] NULL,
	[O17] [int] NULL,
	[O18] [int] NULL,
	[O19] [int] NULL,
	[O20] [int] NULL,
	[O21] [int] NULL,
	[O22] [int] NULL,
	[O23] [int] NULL,
	[O24] [int] NULL,
	[O25] [int] NULL,
	[O26] [int] NULL,
	[O27] [int] NULL,
	[O28] [int] NULL,
	[O29] [int] NULL,
	[O30] [int] NULL,
	[FRONTLINE_DATE] [datetime2](7) NULL,
 CONSTRAINT [PK_ACTIVITY_HISTORY_NET_ID_CUT_OFF_DATE_SEQ] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[NET_ID] ASC,
	[CUT_OFF_DATE] ASC,
	[SEQ] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[ACTIVITY_TEXTS]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[ACTIVITY_TEXTS](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[NET_ID] [int] NOT NULL,
	[FIELD_NR] [int] NOT NULL,
	[FIELD_VALUE] [nvarchar](1000) NULL,
 CONSTRAINT [PK_ACTIVITY_TEXTS_NET_ID_SEQ_FIELD_NR] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[NET_ID] ASC,
	[SEQ] ASC,
	[FIELD_NR] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[AVAILABLE_OUTLINE]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[AVAILABLE_OUTLINE](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[NET_ID] [int] NOT NULL,
	[FIELD_NO] [int] NOT NULL,
	[OC_LEVEL] [int] NOT NULL,
	[OC_SHORT] [nvarchar](255) NOT NULL,
	[AVAIL_FROM] [datetime2](7) NULL,
	[AVAIL_UNTIL] [datetime2](7) NULL,
	[AVAIL_QTY] [float] NOT NULL,
	[WPN] [int] NULL
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[AVAILABLE_REF]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[AVAILABLE_REF](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[NET_ID] [int] NOT NULL,
	[FIELD_NO] [int] NOT NULL,
	[REF_SEQ] [int] NOT NULL,
	[AVAIL_FROM] [datetime2](7) NULL,
	[AVAIL_UNTIL] [datetime2](7) NULL,
	[AVAIL_QTY] [float] NOT NULL,
	[WPN] [int] NULL
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[BASELINE_A]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[BASELINE_A](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[BASELINE_ID] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[AN] [nvarchar](50) NULL,
	[DU] [int] NULL,
	[PC] [float] NULL,
	[RDU] [int] NULL,
	[WPN] [int] NULL,
	[TSE] [datetime2](7) NULL,
	[TSL] [datetime2](7) NULL,
	[TCE] [datetime2](7) NULL,
	[TCL] [datetime2](7) NULL,
	[ACS] [datetime2](7) NULL,
	[ACF] [datetime2](7) NULL,
	[ES] [datetime2](7) NULL,
	[EF] [datetime2](7) NULL,
	[LS] [datetime2](7) NULL,
	[LF] [datetime2](7) NULL,
	[TF] [int] NULL,
	[FF] [int] NULL,
	[DES] [nvarchar](255) NULL,
	[SUBNET_ID] [int] NULL,
	[NET_ID] [int] NULL,
	[N1] [float] NULL,
	[N2] [float] NULL,
	[N3] [float] NULL,
	[N4] [float] NULL,
	[I1] [int] NULL,
	[I2] [int] NULL,
	[I3] [int] NULL,
	[I4] [int] NULL,
	[ON_TARGET] [int] NULL,
	[JOBFLAG] [int] NULL,
	[CURRENT_PROGRESS] [float] NULL,
	[CANCELLED] [datetime2](7) NULL,
	[APPROVED_VO_QTY] [float] NULL,
	[ESTIMATED_VO_QTY] [float] NULL,
	[SUBCONTR_VO_QTY] [float] NULL,
	[INTERNAL_VO_QTY] [float] NULL,
	[JOBPACK_EST_QTY] [float] NULL,
	[EXPENDED_QTY] [float] NULL,
	[CSH] [float] NULL,
	[RSH] [float] NULL,
	[TSH] [float] NULL,
	[ESA] [datetime2](7) NULL,
	[FSD] [datetime2](7) NULL,
	[FFD] [datetime2](7) NULL,
	[CURRENT_PC] [float] NULL,
	[OUT_OF_SYNC] [int] NULL,
 CONSTRAINT [PK_BASELINE_A_BASELINE_ID_SEQ] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[BASELINE_ID] ASC,
	[SEQ] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[BASELINE_DIBB]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[BASELINE_DIBB](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[AN_SEQ] [int] NOT NULL,
	[RES_SEQ] [int] NOT NULL,
	[NET_ID] [int] NOT NULL,
	[BASELINE_ID] [int] NOT NULL,
	[PL_EARNED_EARLY] [float] NULL,
	[PL_EARNED_LATE] [float] NULL,
	[PL_C_EARNED_EARLY] [float] NULL,
	[PL_C_EARNED_LATE] [float] NULL,
 CONSTRAINT [PK_BASELINE_DIBB_SEQ_BASELINE_ID] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[SEQ] ASC,
	[BASELINE_ID] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[BASELINE_LOG]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[BASELINE_LOG](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[BASELINE_ID] [int] NOT NULL,
	[BASELINE_REV] [nvarchar](10) NOT NULL,
	[BASELINE_DATO] [datetime2](7) NOT NULL,
	[CUT_OFF] [datetime2](7) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NULL,
	[LOGIN_NAME] [nvarchar](200) NOT NULL,
	[NET_ID] [int] NULL,
	[CURRENT_RDU] [float] NULL,
	[PLAN_TYPE] [float] NULL,
 CONSTRAINT [PK_BASELINE_LOG_BASELINE_ID] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[BASELINE_ID] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[CALENDARS]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[CALENDARS](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[CAL_ID] [int] NOT NULL,
	[CAL_NAME] [nvarchar](240) NOT NULL,
	[CAL_START] [datetime2](7) NOT NULL,
	[CAL_FINISH] [datetime2](7) NOT NULL,
	[OWNER] [nvarchar](200) NOT NULL,
	[CAL_TYPE] [nvarchar](1) NULL,
 CONSTRAINT [PK_CALENDARS_CAL_ID] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[CAL_ID] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[CODESET]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[CODESET](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[CONFIG_ID] [int] NOT NULL,
	[CODE] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](255) NULL,
	[SHORT] [nvarchar](50) NULL,
	[RFIELD_NR] [int] NOT NULL,
	[SORT_FIELD] [int] NULL,
 CONSTRAINT [PK_CODESET_CONFIG_ID_CODE_RFIELD_NR] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[CONFIG_ID] ASC,
	[CODE] ASC,
	[RFIELD_NR] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[HISTORY_A]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[HISTORY_A](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[NET_ID] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[AN] [nvarchar](50) NOT NULL,
	[DU] [int] NULL,
	[WPN] [int] NULL,
	[ESA] [datetime2](7) NULL,
	[EF] [datetime2](7) NULL,
	[DES] [nvarchar](255) NULL,
	[CURRENT_AS] [datetime2](7) NULL,
	[CURRENT_AF] [datetime2](7) NULL,
	[CURRENT_PROGRESS] [float] NULL,
	[APPROVED_VO_QTY] [float] NULL,
	[ESTIMATED_VO_QTY] [float] NULL,
	[SUBCONTR_VO_QTY] [float] NULL,
	[INTERNAL_VO_QTY] [float] NULL,
	[BASE_PLANNED_PROG] [float] NULL,
	[BES] [datetime2](7) NULL,
	[BEF] [datetime2](7) NULL,
	[CES] [datetime2](7) NULL,
	[CEF] [datetime2](7) NULL,
	[CSH] [float] NULL,
	[RSH] [float] NULL,
	[TSH] [float] NULL,
	[CURR_FRONTLINE_DATE] [datetime2](7) NULL,
	[EXPENDED_QTY] [float] NULL,
	[R1] [int] NULL,
	[R2] [int] NULL,
	[R3] [int] NULL,
	[R4] [int] NULL,
	[R5] [int] NULL,
	[R6] [int] NULL,
	[R7] [int] NULL,
	[R8] [int] NULL,
	[R9] [int] NULL,
	[R10] [int] NULL,
	[R11] [int] NULL,
	[R12] [int] NULL,
	[R13] [int] NULL,
	[R14] [int] NULL,
	[R15] [int] NULL,
	[R16] [int] NULL,
	[R17] [int] NULL,
	[R18] [int] NULL,
	[R19] [int] NULL,
	[R20] [int] NULL,
	[R21] [int] NULL,
	[R22] [int] NULL,
	[R23] [int] NULL,
	[R24] [int] NULL,
	[R25] [int] NULL,
	[R26] [int] NULL,
	[R27] [int] NULL,
	[R28] [int] NULL,
	[R29] [int] NULL,
	[R30] [int] NULL,
	[F1] [nvarchar](255) NULL,
	[F2] [nvarchar](255) NULL,
	[F3] [nvarchar](255) NULL,
	[F4] [nvarchar](255) NULL,
	[F5] [nvarchar](255) NULL,
	[F6] [nvarchar](50) NULL,
	[F7] [nvarchar](50) NULL,
	[F8] [nvarchar](50) NULL,
	[F9] [nvarchar](50) NULL,
	[F10] [nvarchar](20) NULL,
	[F11] [nvarchar](20) NULL,
	[F12] [nvarchar](20) NULL,
	[F13] [nvarchar](20) NULL,
	[F14] [nvarchar](20) NULL,
	[F15] [nvarchar](20) NULL,
	[F16] [nvarchar](20) NULL,
	[F17] [nvarchar](20) NULL,
	[F18] [nvarchar](20) NULL,
	[F19] [nvarchar](20) NULL,
	[F20] [nvarchar](20) NULL,
	[CANCELLED] [datetime2](7) NULL,
 CONSTRAINT [PK_HISTORY_A_SEQ_NET_ID] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[SEQ] ASC,
	[NET_ID] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[MP_MASTER]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[MP_MASTER](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[MP_ID] [int] NOT NULL,
	[MP_NAME] [nvarchar](50) NOT NULL,
	[MP_DESCRIPTION] [nvarchar](255) NULL,
	[MP_RESOURCESET] [int] NOT NULL,
	[MP_CODESET] [int] NOT NULL,
	[MP_PROFILESET] [int] NOT NULL,
	[MP_SYMBOLSET] [int] NOT NULL,
	[MP_TITLE] [nvarchar](100) NULL,
	[MP_CLIENT] [nvarchar](50) NULL,
	[MP_COMPANY] [nvarchar](50) NULL,
	[LOGO1] [nvarchar](100) NULL,
	[LOGO2] [nvarchar](100) NULL,
	[FREETEXT1] [nvarchar](255) NULL,
	[FREETEXT2] [nvarchar](255) NULL,
	[FREETEXT3] [nvarchar](255) NULL,
	[FREETEXT4] [nvarchar](255) NULL,
	[OWNER] [nvarchar](200) NULL,
	[SCH_OPT] [int] NULL,
	[SCH_MAX_DELAY] [int] NULL,
	[SCH_OVERLOAD_LIM] [int] NULL,
	[SCH_OVERLOAD_OPT] [int] NULL,
	[AVA_METHOD] [int] NULL,
	[SCH_FILTER] [nvarchar](2000) NULL,
	[SCH_SORT] [nvarchar](100) NULL,
 CONSTRAINT [PK_MP_MASTER_MP_ID] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[MP_ID] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[MP_MEMBER]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[MP_MEMBER](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[MP_ID] [int] NOT NULL,
	[NET_ID] [int] NOT NULL,
	[NET_NO] [int] NULL,
	[CAL_NO] [float] NULL,
	[PROFILE_NO] [float] NULL,
 CONSTRAINT [PK_MP_MEMBER_MP_ID_NET_ID] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[MP_ID] ASC,
	[NET_ID] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[MSP_UFIELD_MAPPING]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[MSP_UFIELD_MAPPING](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[UF_MAP_UID] [int] NOT NULL,
	[SAFRAN_FIELD_NO] [nvarchar](10) NOT NULL,
	[MSP_FIELD_NO] [int] NULL,
	[MSP_IS_ENTERPRISE] [int] NULL,
 CONSTRAINT [PK_MSP_UFIELD_MAPPING_UF_MAP_UID_SAFRAN_FIELD_NO] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[UF_MAP_UID] ASC,
	[SAFRAN_FIELD_NO] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[NETWORKS]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[NETWORKS](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[NET_ID] [int] NOT NULL,
	[NAME] [nvarchar](200) NOT NULL,
	[DESCRIPTION] [nvarchar](200) NULL,
	[ANA_DATE] [datetime2](7) NULL,
	[ANA_TNOW] [datetime2](7) NULL,
	[USER_ID] [int] NULL,
	[NA_DATE] [datetime2](7) NULL,
	[USER_NAME] [nvarchar](200) NULL,
	[CAL_ID] [int] NOT NULL,
	[PROFILESET] [int] NULL,
	[CODESET] [int] NULL,
	[ANA_OFF] [int] NOT NULL,
	[PROJECT_ID] [int] NULL,
	[DERIVED_FROM] [int] NULL,
	[STRETCH] [int] NOT NULL,
	[LONGEST_PATH] [int] NOT NULL,
	[FLOAT_OPT] [int] NOT NULL,
	[DEPENDENCIES] [int] NOT NULL,
	[PROGRESS] [int] NOT NULL,
	[SAVE_ANA_FLAG] [int] NULL,
	[SCH_OPT] [int] NULL,
	[SCH_MAX_DELAY] [int] NULL,
	[SCH_OVERLOAD_LIM] [int] NULL,
	[SCH_OVERLOAD_OPT] [int] NULL,
	[CALC_ID] [int] NULL,
	[SAVE_RESOURCE_FLAG] [int] NULL,
	[LOCK_SCOPE] [int] NULL,
	[AUTO_SUM_SCOPE] [int] NULL,
	[RESOURCE_SET] [int] NULL,
	[SYMBOL_SET] [int] NULL,
	[OS_SCOPE] [int] NULL,
	[DISABLE_SPLIT_TARGETS] [int] NULL,
	[SCH_FILTER] [nvarchar](2000) NULL,
	[SCH_SORT] [nvarchar](100) NULL,
	[GSID] [int] NULL,
	[PROG_HANDLING_METHOD] [int] NULL,
	[RATE_TYPE] [int] NULL,
	[RATE_SET] [int] NULL,
	[BSCOPE] [float] NULL,
	[BPLANNED] [float] NULL,
	[BEARNED] [float] NULL,
	[EXPENDED] [float] NULL,
	[IS_TEMPLATE] [int] NULL,
	[STATUS_METHOD] [int] NULL,
	[STATUS_METHOD_OPTION] [int] NULL,
	[STATUS_METHOD_INTV] [int] NULL,
 CONSTRAINT [PK_NETWORKS_NET_ID] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[NET_ID] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[OUTLINE_CODES]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[OUTLINE_CODES](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[CONFIG_ID] [int] NOT NULL,
	[OC_FIELD] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[PARENT_SEQ] [int] NOT NULL,
	[SHORT] [nvarchar](100) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NULL,
	[SORT_FIELD] [int] NULL,
 CONSTRAINT [PK_OUTLINE_CODES_CONFIG_ID_OC_FIELD_SEQ] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[CONFIG_ID] ASC,
	[OC_FIELD] ASC,
	[SEQ] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
/****** Object:  Table [safran].[RESOURCES]    Script Date: 29.10.2019 22:39:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [safran].[RESOURCES](
	[META_ORAROWSCN] [bigint] NULL,
    [META_SourceDatabase] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[AN_SEQ] [int] NOT NULL,
	[RES_SEQ] [int] NOT NULL,
	[QTY] [float] NULL,
	[DUR] [int] NULL,
	[LAGR] [int] NULL,
	[TYPE] [int] NULL,
	[PROFILE] [int] NULL,
	[VO_SEQ] [int] NULL,
	[CURRENT_PROGRESS] [float] NULL,
	[ACTUAL_QTY] [float] NULL,
	[JOBPACK_EST_QTY] [float] NULL,
	[WPN] [int] NULL,
	[QTY1] [float] NULL,
	[CSH_FLAG] [int] NULL,
	[RSH_FLAG] [int] NULL,
	[TSH_FLAG] [int] NULL,
	[NET_ID] [int] NOT NULL,
	[EARNED_JOB_QTY] [float] NULL,
	[ESAR] [datetime2](7) NULL,
	[EFR] [datetime2](7) NULL,
	[LSR] [datetime2](7) NULL,
	[LFR] [datetime2](7) NULL,
	[COST] [float] NULL,
	[COST1] [float] NULL,
	[COST_RATE] [float] NULL,
	[COST_ACTUAL] [float] NULL,
	[PL_PROG_CUM_EARLY] [float] NULL,
	[FCQTY] [float] NULL,
	[FCLAG] [float] NULL,
	[FCDUR] [float] NULL,
	[DUR_FMT] [int] NULL,
	[EXT_SEQ] [int] NULL,
 CONSTRAINT [PK_RESOURCES_SEQ_NET_ID] PRIMARY KEY CLUSTERED 
(
    [META_SourceDatabase] ASC,
	[SEQ] ASC,
	[NET_ID] ASC)
) ON PS_SOURCE_DATABASE ([META_SourceDatabase])
GO
