/****** Object:  View [om].[Planning_Activities_OPT]    Script Date: 07.01.2020 13:46:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [om].[Planning_Activities_OPT] /* WITH SCHEMABINDING */ AS
SELECT
  actTextWo.FieldValue as WorkOrderNum,
  actTextWo.NetworkId as WoNetworkId,
  actText.FieldValue as ShortText,
  actText.NetworkId as ShortTextNetWorkId,
  c29.ShortCode as SapSystemNumber,
  c6.ShortCode as Wind,
  c26.ShortCode as RevCode,
  c19.ShortCode as FunctLoc,
  c8.ShortCode as ProdArea,
  c27.ShortCode as MainWC,
  c5.ShortCode as WOEquipmentType,
  c7.ShortCode as WOContractor,
  [ActivityId],
  [ActivityNumber],
  [Duration],
  [PercentComplete],
  [RemainingDuration],
  [WorkPattern],
  [TargetStartEarly],
  [TargetStartLate],
  [TargetCompleteEarly],
  [TargetCompleteLate],
  [ActualStart],
  [ActualFinish],
  act.[Description],
  [EarlyStart],
  [EarlyFinish],
  [LateStart],
  [LateFinish],
  [TotalFloat],
  [FreeFloat],
  [SubnetId],
  [NetId],
  [Hovedgruppe],
  [Prosjekt],
  [Type],
  [Lag],
  [EquipmentType],
  [Window],
  [Contractor],
  [ProductionArea],
  [WorkArea],
  [Coordinator],
  [Tarmon],
  [Gruppe],
  [ReasonforChange],
  [SAPPersonRes],
  [SAPWSCStatus],
  [MaterialStatus],
  [SAPABCIndicator],
  [SAPMPG],
  [SAPFL],
  [SAPPlant],
  [SAPStTextK],
  [SAPPrioritet],
  [SAPLocation],
  [SAPWOType],
  [SAPFase],
  [SAPRevisjonsKode],
  [SAPMWC],
  [SAPOWC],
  [SAPSystem],
  [Reservert30],
  [Date1],
  [Date2],
  [ProgressUpdated],
  [Date4],
  [Date5],
  [Date6],
  [Date7],
  [Date8],
  [SAPNotifdate],
  [SAPReqEnd],
  [OverfDatofraSAP],
  [SAPOrderFinish],
  [SAPConstrStart],
  [SAPConstrFinish],
  [Date15],
  [Date16],
  [SistEndretiSAP],
  [SAPBasicStartDate],
  [SAPImportES],
  [SAPImportEF],
  [Decimal1],
  [Decimal2],
  [Decimal3],
  [Decimal4],
  [Decimal5],
  [Decimal6],
  [Decimal7],
  [SAPActualMhrs],
  [SAPRemMhrs],
  [SAPPlanMhrs],
  [Decimal11],
  [Decimal12],
  [Decimal13],
  [Decimal14],
  [Decimal15],
  [Decimal16],
  [Decimal17],
  [Decimal18],
  [SAPWSCHighestSc],
  [Manpower],
  [Flag1],
  [Flag2],
  [Flag3],
  [L4Criticalpath],
  [SAPProdcrit],
  [SAPSafetycrit],
  [SAPCMRIndic],
  [SlettetiSAP],
  [QTYfraSAP],
  [OppdaterSAP],
  [DURfraSAP],
  [Stillasbehov],
  [InklSAPConstrDato],
  [SAPWorkPermit],
  [SAPSJA],
  [SAPKilde],
  [Årsplan],
  [IkkepåDAP],
  [OPSPlan],
  [NyfraSAP],
  [OnTarget],
  [JobFlag],
  [CurrentProgress],
  [FrontlineDate],
  [CancelledDate],
  [Remarks],
  [OriginalQty],
  [ApprovedVoQty],
  [EstimatedVoQty],
  [SubcontrVoQty],
  [InternalVoQty],
  [JobpackEstQty],
  [ExpendedQty],
  [EarlyStartActual],
  [CurrentActualStart],
  [CurrentActualFinish],
  [CurrentPlannedProgress],
  [BaselinePlannedProgress],
  [OriginalEarlyStart],
  [OriginalEarlyFinish],
  [OriginalLateStart],
  [OriginalLateFinish],
  [BaselineEarlyStart],
  [BaselineEarlyStartAnalysed],
  [BaselineEarlyFinish],
  [BaselineLateStart],
  [BaselineLateFinish],
  [CurrentEarlyStart],
  [CurrentEarlyFinish],
  [CurrentLateStart],
  [CurrentLateFinish],
  [OriginalQty1],
  [BaselineScope],
  [CurrentScope],
  [TotalScope],
  [CurrentFrontlineDate],
  [EarlyStartScheduled],
  [EarlyFinishScheduled],
  [TotalFloatScheduled],
  [FreeFloatScheduled],
  [HammockFlag],
  [AnalyseOpt],
  [FixedStartDate],
  [FixedFinishDate],
  [ManualProgressFlag],
  [CurrentPercentComplete],
  [RemainingDurationAnalysed],
  [CurrentEarlyStartActual],
  [CurrentTotalFloat],
  [CurrentFreeFloat],
  [LivePlanOutOfSequenceFlag],
  [CurrentPlanOutOfSequenceFlag],
  [ProgressOutOfSyncFlag],
  [ForecastDuration],
  [ForecastPlanEarlyStartActual],
  [ForecastPlanEarlyFinish],
  [RevisedPlanEarlyStartActual],
  [RevisedPlanEarlyStart],
  [RevisedPlanEarlyFinish],
  [RevisedPlanLateStart],
  [RevisedPlanLateFinish],
  [RevisedPlannedProgress],
  [ProgressFrontlineRevisedPlan],
  [ForecastQty],
  [DurationFormat],
  [OutlineCode1],
  [OutlineCode2],
  [OutlineCode3],
  [OutlineCode4],
  [OutlineCode5],
  [OutlineCode6],
  [OutlineCode7],
  [OutlineCode8],
  [OutlineCode9],
  [OutlineCode10],
  [OutlineCode11],
  [OutlineCode12],
  [OutlineCode13],
  [OutlineCode14],
  [OutlineCode15],
  [OutlineCode16],
  [OutlineCode17],
  [OutlineCode18],
  [OutlineCode19],
  [OutlineCode20],
  [OutlineCode21],
  [OutlineCode22],
  [OutlineCode23],
  [OutlineCode24],
  [OutlineCode25],
  [OutlineCode26],
  [OutlineCode27],
  [OutlineCode28],
  [OutlineCode29],
  [SAPWBS],
  [RowNo],
  [OutlineLevel],
  [LinkSummary],
  [ComputedPercentComplete],
  [RevisedScope],
  [Duration1],
  [Duration2],
  [Duration3],
  [Duration4],
  [Duration5],
  [Duration6],
  [Duration7],
  [Duration8],
  [Duration9],
  [SAPDuration],
  [EarnedValueMethod],
  [EarnedValueMethodParameter],
  [MinimumDuration],
  [ActivityExistenceFlag],
  [ActivityDurationFitFlag],
  [AsLateAsPossibleConstraintFlag],
  [ActivityType],
  [MinimumContinuousDuration],
  [Supplier],
  [Phase],
  [Reference33],
  [Reference34],
  [Reference35],
  [Reference36],
  [Reference37],
  [Reference38],
  [Reference39],
  [Reference40],
  [Reference41],
  [Reference42],
  [Reference43],
  [Reference44],
  [Reference45],
  [Reference46],
  [Reference47],
  [Reference48],
  [Reference49],
  [Reference50],
  [Reference51],
  [Reference52],
  [Reference53],
  [Reference54],
  [Reference55],
  [Reference56],
  [Reference57],
  [Reference58],
  [Reference59],
  [WON],
  [Date21],
  [Date22],
  [Date23],
  [Date24],
  [Date25],
  [Date26],
  [Date27],
  [Date28],
  [Date29],
  [Date30],
  [Date31],
  [Date32],
  [Date33],
  [Date34],
  [Date35],
  [Date36],
  [Date37],
  [Date38],
  [Date39],
  [Date40],
  [CURRENT_RDU],
  [ESAS]
FROM
  [om].[Planning_Activities] act
  left join om.Planning_ActivityTexts actText on act.ActivityId = actText.SequenceNumber
  and actText.NetworkId = act.NetId
  and actText.FieldNr = 2
  left join om.Planning_ActivityTexts actTextWo on act.ActivityId = actTextWo.SequenceNumber
  and actTextWo.NetworkId = act.NetId
  and actTextWo.FieldNr = 22
  left join om.Planning_CodeSets c29 on c29.InternalId = act.SAPSystem
  and c29.CodeSetId = 121
  and c29.ReferenceFieldNumberNetwork = 29
  left join om.Planning_CodeSets c26 on c26.InternalId = act.SAPRevisjonsKode
  and c26.CodesetId = 121
  and c26.ReferenceFieldNumberNetwork = 26
  left join om.Planning_CodeSets c19 on c19.InternalId = act.SAPFL
  and c19.CodesetId = 121
  and c19.ReferenceFieldNumberNetwork = 19
  left join om.Planning_CodeSets c8 on c8.InternalId = act.ProductionArea
  and c8.CodesetId = 121
  and c8.ReferenceFieldNumberNetwork = 8
  left join om.Planning_CodeSets c27 on c27.InternalId = act.SAPMWC
  and c27.CodesetId = 121
  and c27.ReferenceFieldNumberNetwork = 27
  left join om.Planning_CodeSets c5 on c5.InternalId = act.EquipmentType
  and c5.CodesetId = 121
  and c5.ReferenceFieldNumberNetwork = 5
  left join om.Planning_CodeSets c6 on c6.InternalId = act.Window
  and c6.CodesetId = 121
  and c6.ReferenceFieldNumberNetwork = 6
  left join om.Planning_CodeSets c7 on c7.InternalId = act.Contractor
  and c7.CodesetId = 121
  and c7.ReferenceFieldNumberNetwork = 7
GO


