INSERT [Any2Omnia].[Jobs] ([JobName], [SourceDatabase], [SourceSystemName], [UniqueId], [SourceType], [ConnectionSecretKey], [AzureSQLServer], [AzureSQLDB], [FolderTemplate], [PreJobSP], [PostJobSP], [Enabled]) VALUES (N'Safran', 299, N'Safran', N'Safran', N'Oracle', N'ora-safranproject-dev', N'dataengineeringsqldev.database.windows.net', N'SAFRANPROJECT', N'/raw/corporate/SAFRANPROJECT/%SourceDatabase%/%YY%/%MM%/%DD%', NULL, NULL, 1)
GO
INSERT [Any2Omnia].[Jobs] ([JobName], [SourceDatabase], [SourceSystemName], [UniqueId], [SourceType], [ConnectionSecretKey], [AzureSQLServer], [AzureSQLDB], [FolderTemplate], [PreJobSP], [PostJobSP], [Enabled]) VALUES (N'Safran-p296-DPB', 296, N'Safran', N'Safran-p296-DPB', N'Oracle', N'ora-safranproject-p296-dev', N'dataengineeringsqldev.database.windows.net', N'SAFRANPROJECT', N'/raw/corporate/SAFRANPROJECT/%SourceDatabase%/%YY%/%MM%/%DD%', NULL, NULL, 1)
GO
INSERT [Any2Omnia].[Jobs] ([JobName], [SourceDatabase], [SourceSystemName], [UniqueId], [SourceType], [ConnectionSecretKey], [AzureSQLServer], [AzureSQLDB], [FolderTemplate], [PreJobSP], [PostJobSP], [Enabled]) VALUES (N'Safran-p300-MMP', 300, N'Safran', N'Safran-p300-MMP', N'Oracle', N'ora-safranproject-p300-dev', N'dataengineeringsqldev.database.windows.net', N'SAFRANPROJECT', N'/raw/corporate/SAFRANPROJECT/%SourceDatabase%/%YY%/%MM%/%DD%', NULL, NULL, 1)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'ACT_IMPACT', N'safran', N'safran_staging', N'ACT_IMPACT', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACT_IMPACT T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:34:48.0000000' AS DateTime2), CAST(N'2019-11-06T21:35:17.0000000' AS DateTime2), CAST(N'2019-11-02T02:05:18.0000000' AS DateTime2), 47241, 48962, 1, 131571378)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'ACT_RISK', N'safran', N'safran_staging', N'ACT_RISK', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACT_RISK T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:34:37.0000000' AS DateTime2), CAST(N'2019-11-06T21:35:01.0000000' AS DateTime2), CAST(N'2019-11-02T02:07:32.0000000' AS DateTime2), 1471499, 2810695, 1, 684827010)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'ACTIVITIES', N'safran', N'safran_staging', N'ACTIVITIES', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITIES T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:34:39.0000000' AS DateTime2), CAST(N'2019-11-06T21:35:14.0000000' AS DateTime2), CAST(N'2019-11-02T01:43:39.0000000' AS DateTime2), 1913533, 3482027, 1, 684827081)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'ACTIVITIES_TEMP', N'safran', N'safran_staging', N'ACTIVITIES_TEMP', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITIES_TEMP T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:34:39.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:35:03.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'ACTIVITY_BARS', N'safran', N'safran_staging', N'ACTIVITY_BARS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITY_BARS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:36:01.0000000' AS DateTime2), CAST(N'2019-11-06T21:36:30.0000000' AS DateTime2), CAST(N'2019-11-02T02:06:25.0000000' AS DateTime2), 196, 58842, 1, 661128489)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'ACTIVITY_HISTORY', N'safran', N'safran_staging', N'ACTIVITY_HISTORY', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITY_HISTORY T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:35:42.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:36:11.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'ACTIVITY_TEXTS', N'safran', N'safran_staging', N'ACTIVITY_TEXTS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITY_TEXTS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:37:07.0000000' AS DateTime2), CAST(N'2019-11-06T21:37:43.0000000' AS DateTime2), CAST(N'2019-11-02T01:49:55.0000000' AS DateTime2), 2915493, 8664044, 1, 684826834)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'AVAILABLE_OUTLINE', N'safran', N'safran_staging', N'AVAILABLE_OUTLINE', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.AVAILABLE_OUTLINE T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:35:35.0000000' AS DateTime2), CAST(N'2019-11-06T21:35:59.0000000' AS DateTime2), CAST(N'2019-11-02T02:06:49.0000000' AS DateTime2), 4, 5716, 1, 75943921)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'AVAILABLE_REF', N'safran', N'safran_staging', N'AVAILABLE_REF', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.AVAILABLE_REF T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:36:57.0000000' AS DateTime2), CAST(N'2019-11-06T21:37:20.0000000' AS DateTime2), CAST(N'2019-11-02T02:07:23.0000000' AS DateTime2), 21, 7165, 1, 122869189)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'BASELINE_A', N'safran', N'safran_staging', N'BASELINE_A', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.BASELINE_A T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:36:48.0000000' AS DateTime2), CAST(N'2019-11-06T21:37:14.0000000' AS DateTime2), CAST(N'2019-11-02T02:11:59.0000000' AS DateTime2), 649866, 833772, 1, 681364090)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'BASELINE_DIBB', N'safran', N'safran_staging', N'BASELINE_DIBB', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.BASELINE_DIBB T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:38:50.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:39:16.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'BASELINE_LOG', N'safran', N'safran_staging', N'BASELINE_LOG', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.BASELINE_LOG T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:36:39.0000000' AS DateTime2), CAST(N'2019-11-06T21:37:05.0000000' AS DateTime2), CAST(N'2019-11-02T02:07:46.0000000' AS DateTime2), 98, 246, 1, 681364090)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'CALENDARS', N'safran', N'safran_staging', N'CALENDARS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.CALENDARS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:37:47.0000000' AS DateTime2), CAST(N'2019-11-06T21:38:20.0000000' AS DateTime2), CAST(N'2019-11-02T02:08:28.0000000' AS DateTime2), 425, 692, 1, 684564793)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'CODESET', N'safran', N'safran_staging', N'CODESET', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.CODESET T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:37:45.0000000' AS DateTime2), CAST(N'2019-11-06T21:38:11.0000000' AS DateTime2), CAST(N'2019-11-02T02:16:20.0000000' AS DateTime2), 1414721, 2340914, 1, 684771524)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'HISTORY_A', N'safran', N'safran_staging', N'HISTORY_A', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.HISTORY_A T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:39:50.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:40:20.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'MP_MASTER', N'safran', N'safran_staging', N'MP_MASTER', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.MP_MASTER T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:37:38.0000000' AS DateTime2), CAST(N'2019-11-06T21:38:01.0000000' AS DateTime2), CAST(N'2019-11-02T02:08:39.0000000' AS DateTime2), 8, 20, 1, 681368834)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'MP_MEMBER', N'safran', N'safran_staging', N'MP_MEMBER', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.MP_MEMBER T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:38:51.0000000' AS DateTime2), CAST(N'2019-11-06T21:39:14.0000000' AS DateTime2), CAST(N'2019-11-02T02:09:29.0000000' AS DateTime2), 17, 221, 1, 684310119)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'MSP_UFIELD_MAPPING', N'safran', N'safran_staging', N'MSP_UFIELD_MAPPING', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.MSP_UFIELD_MAPPING T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:38:52.0000000' AS DateTime2), CAST(N'2019-11-06T21:39:26.0000000' AS DateTime2), CAST(N'2019-11-02T02:17:34.0000000' AS DateTime2), 150, 450, 1, 147120701)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'NETWORKS', N'safran', N'safran_staging', N'NETWORKS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.NETWORKS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:41:02.0000000' AS DateTime2), CAST(N'2019-11-06T21:41:29.0000000' AS DateTime2), CAST(N'2019-11-02T01:52:45.0000000' AS DateTime2), 333, 666, 1, 684827081)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'OUTLINE_CODES', N'safran', N'safran_staging', N'OUTLINE_CODES', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.OUTLINE_CODES T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:38:35.0000000' AS DateTime2), CAST(N'2019-11-06T21:39:03.0000000' AS DateTime2), CAST(N'2019-11-02T02:12:56.0000000' AS DateTime2), 1930197, 3193343, 1, 684621068)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran', N'SAFRANSA', N'RESOURCES', N'safran', N'safran_staging', N'RESOURCES', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.RESOURCES T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:39:56.0000000' AS DateTime2), CAST(N'2019-11-06T21:40:20.0000000' AS DateTime2), CAST(N'2019-11-02T02:15:51.0000000' AS DateTime2), 2131648, 3363713, 1, 684829161)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'ACT_IMPACT', N'safran', N'safran_staging', N'ACT_IMPACT', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACT_IMPACT T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:43:40.0000000' AS DateTime2), CAST(N'2019-11-06T21:44:11.0000000' AS DateTime2), CAST(N'2019-11-01T17:38:02.0000000' AS DateTime2), 0, 48962, 1, 131571378)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'ACT_RISK', N'safran', N'safran_staging', N'ACT_RISK', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACT_RISK T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:43:41.0000000' AS DateTime2), CAST(N'2019-11-06T21:44:26.0000000' AS DateTime2), CAST(N'2019-11-01T17:38:30.0000000' AS DateTime2), 147776, 2810695, 1, 684830146)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'ACTIVITIES', N'safran', N'safran_staging', N'ACTIVITIES', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITIES T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:28:45.0000000' AS DateTime2), CAST(N'2019-11-06T21:29:13.0000000' AS DateTime2), CAST(N'2019-11-01T17:42:31.0000000' AS DateTime2), 161906, 3482027, 1, 684827081)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'ACTIVITIES_TEMP', N'safran', N'safran_staging', N'ACTIVITIES_TEMP', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITIES_TEMP T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:43:32.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:44:06.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'ACTIVITY_BARS', N'safran', N'safran_staging', N'ACTIVITY_BARS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITY_BARS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:29:42.0000000' AS DateTime2), CAST(N'2019-11-06T21:30:12.0000000' AS DateTime2), CAST(N'2019-11-01T17:38:59.0000000' AS DateTime2), 0, 58801, 1, 661128489)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'ACTIVITY_HISTORY', N'safran', N'safran_staging', N'ACTIVITY_HISTORY', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITY_HISTORY T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:29:33.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:30:02.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'ACTIVITY_TEXTS', N'safran', N'safran_staging', N'ACTIVITY_TEXTS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITY_TEXTS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:30:34.0000000' AS DateTime2), CAST(N'2019-11-06T21:31:03.0000000' AS DateTime2), CAST(N'2019-11-01T17:46:43.0000000' AS DateTime2), 730560, 8664044, 1, 684826834)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'AVAILABLE_OUTLINE', N'safran', N'safran_staging', N'AVAILABLE_OUTLINE', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.AVAILABLE_OUTLINE T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:29:40.0000000' AS DateTime2), CAST(N'2019-11-06T21:30:09.0000000' AS DateTime2), CAST(N'2019-11-01T17:39:09.0000000' AS DateTime2), 0, 5712, 1, 75943921)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'AVAILABLE_REF', N'safran', N'safran_staging', N'AVAILABLE_REF', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.AVAILABLE_REF T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:30:53.0000000' AS DateTime2), CAST(N'2019-11-06T21:31:20.0000000' AS DateTime2), CAST(N'2019-11-01T17:40:16.0000000' AS DateTime2), 0, 7160, 1, 122869189)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'BASELINE_A', N'safran', N'safran_staging', N'BASELINE_A', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.BASELINE_A T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:30:37.0000000' AS DateTime2), CAST(N'2019-11-06T21:31:09.0000000' AS DateTime2), CAST(N'2019-11-01T17:40:47.0000000' AS DateTime2), 23693, 833772, 1, 681364090)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'BASELINE_DIBB', N'safran', N'safran_staging', N'BASELINE_DIBB', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.BASELINE_DIBB T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:32:19.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:32:48.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'BASELINE_LOG', N'safran', N'safran_staging', N'BASELINE_LOG', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.BASELINE_LOG T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:30:46.0000000' AS DateTime2), CAST(N'2019-11-06T21:31:27.0000000' AS DateTime2), CAST(N'2019-11-01T17:40:30.0000000' AS DateTime2), 22, 246, 1, 681364090)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'CALENDARS', N'safran', N'safran_staging', N'CALENDARS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.CALENDARS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:31:59.0000000' AS DateTime2), CAST(N'2019-11-06T21:32:31.0000000' AS DateTime2), CAST(N'2019-11-01T17:41:41.0000000' AS DateTime2), 81, 692, 1, 684564793)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'CODESET', N'safran', N'safran_staging', N'CODESET', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.CODESET T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:31:51.0000000' AS DateTime2), CAST(N'2019-11-06T21:32:22.0000000' AS DateTime2), CAST(N'2019-11-01T17:42:02.0000000' AS DateTime2), 31216, 2340914, 1, 684771524)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'HISTORY_A', N'safran', N'safran_staging', N'HISTORY_A', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.HISTORY_A T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:33:25.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:33:59.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'MP_MASTER', N'safran', N'safran_staging', N'MP_MASTER', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.MP_MASTER T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:32:00.0000000' AS DateTime2), CAST(N'2019-11-06T21:32:32.0000000' AS DateTime2), CAST(N'2019-11-01T17:41:47.0000000' AS DateTime2), 3, 20, 1, 681368834)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'MP_MEMBER', N'safran', N'safran_staging', N'MP_MEMBER', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.MP_MEMBER T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:33:08.0000000' AS DateTime2), CAST(N'2019-11-06T21:33:38.0000000' AS DateTime2), CAST(N'2019-11-01T17:42:49.0000000' AS DateTime2), 0, 221, 1, 684310119)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'MSP_UFIELD_MAPPING', N'safran', N'safran_staging', N'MSP_UFIELD_MAPPING', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.MSP_UFIELD_MAPPING T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:32:52.0000000' AS DateTime2), CAST(N'2019-11-06T21:33:24.0000000' AS DateTime2), CAST(N'2019-11-01T17:43:07.0000000' AS DateTime2), 150, 450, 1, 147120701)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'NETWORKS', N'safran', N'safran_staging', N'NETWORKS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.NETWORKS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:34:43.0000000' AS DateTime2), CAST(N'2019-11-06T21:35:15.0000000' AS DateTime2), CAST(N'2019-11-01T17:50:15.0000000' AS DateTime2), 82, 666, 1, 684827081)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'OUTLINE_CODES', N'safran', N'safran_staging', N'OUTLINE_CODES', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.OUTLINE_CODES T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:33:19.0000000' AS DateTime2), CAST(N'2019-11-06T21:33:59.0000000' AS DateTime2), CAST(N'2019-11-01T17:43:06.0000000' AS DateTime2), 81682, 3193343, 1, 684621068)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p296-DPB', N'SAFRANSA', N'RESOURCES', N'safran', N'safran_staging', N'RESOURCES', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.RESOURCES T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:34:15.0000000' AS DateTime2), CAST(N'2019-11-06T21:34:53.0000000' AS DateTime2), CAST(N'2019-11-01T17:44:27.0000000' AS DateTime2), 101333, 3363713, 1, 684829161)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'ACT_IMPACT', N'safran', N'safran_staging', N'ACT_IMPACT', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACT_IMPACT T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:42:39.0000000' AS DateTime2), CAST(N'2019-11-06T21:43:04.0000000' AS DateTime2), CAST(N'2019-11-01T17:37:49.0000000' AS DateTime2), 1780, 48962, 1, 131571378)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'ACT_RISK', N'safran', N'safran_staging', N'ACT_RISK', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACT_RISK T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:42:40.0000000' AS DateTime2), CAST(N'2019-11-06T21:43:11.0000000' AS DateTime2), CAST(N'2019-11-01T17:39:20.0000000' AS DateTime2), 1185043, 2810695, 1, 684830146)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'ACTIVITIES', N'safran', N'safran_staging', N'ACTIVITIES', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITIES T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:27:37.0000000' AS DateTime2), CAST(N'2019-11-06T21:28:36.0000000' AS DateTime2), CAST(N'2019-11-01T18:00:21.0000000' AS DateTime2), 1400972, 3482027, 1, 684827081)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'ACTIVITIES_TEMP', N'safran', N'safran_staging', N'ACTIVITIES_TEMP', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITIES_TEMP T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:42:42.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:43:13.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'ACTIVITY_BARS', N'safran', N'safran_staging', N'ACTIVITY_BARS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITY_BARS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:43:38.0000000' AS DateTime2), CAST(N'2019-11-06T21:44:11.0000000' AS DateTime2), CAST(N'2019-11-01T17:38:51.0000000' AS DateTime2), 98, 58883, 1, 661128489)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'ACTIVITY_HISTORY', N'safran', N'safran_staging', N'ACTIVITY_HISTORY', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITY_HISTORY T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:43:48.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:44:18.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'ACTIVITY_TEXTS', N'safran', N'safran_staging', N'ACTIVITY_TEXTS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.ACTIVITY_TEXTS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:30:30.0000000' AS DateTime2), CAST(N'2019-11-06T21:31:35.0000000' AS DateTime2), CAST(N'2019-11-01T18:09:55.0000000' AS DateTime2), 5022595, 8664044, 1, 684826834)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'AVAILABLE_OUTLINE', N'safran', N'safran_staging', N'AVAILABLE_OUTLINE', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.AVAILABLE_OUTLINE T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:43:54.0000000' AS DateTime2), CAST(N'2019-11-06T21:44:18.0000000' AS DateTime2), CAST(N'2019-11-01T17:38:56.0000000' AS DateTime2), 4, 5720, 1, 75943921)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'AVAILABLE_REF', N'safran', N'safran_staging', N'AVAILABLE_REF', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.AVAILABLE_REF T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:29:26.0000000' AS DateTime2), CAST(N'2019-11-06T21:29:59.0000000' AS DateTime2), CAST(N'2019-11-01T17:39:41.0000000' AS DateTime2), 19, 7155, 1, 122869189)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'BASELINE_A', N'safran', N'safran_staging', N'BASELINE_A', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.BASELINE_A T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:29:40.0000000' AS DateTime2), CAST(N'2019-11-06T21:30:05.0000000' AS DateTime2), CAST(N'2019-11-01T17:42:08.0000000' AS DateTime2), 164059, 833772, 1, 681364090)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'BASELINE_DIBB', N'safran', N'safran_staging', N'BASELINE_DIBB', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.BASELINE_DIBB T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:32:14.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:32:45.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'BASELINE_LOG', N'safran', N'safran_staging', N'BASELINE_LOG', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.BASELINE_LOG T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:29:35.0000000' AS DateTime2), CAST(N'2019-11-06T21:30:08.0000000' AS DateTime2), CAST(N'2019-11-01T17:40:03.0000000' AS DateTime2), 130, 246, 1, 681364090)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'CALENDARS', N'safran', N'safran_staging', N'CALENDARS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.CALENDARS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:30:32.0000000' AS DateTime2), CAST(N'2019-11-06T21:30:57.0000000' AS DateTime2), CAST(N'2019-11-01T17:40:26.0000000' AS DateTime2), 192, 692, 1, 684564793)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'CODESET', N'safran', N'safran_staging', N'CODESET', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.CODESET T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:30:52.0000000' AS DateTime2), CAST(N'2019-11-06T21:31:16.0000000' AS DateTime2), CAST(N'2019-11-01T17:45:13.0000000' AS DateTime2), 912544, 2340914, 1, 684771524)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'HISTORY_A', N'safran', N'safran_staging', N'HISTORY_A', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.HISTORY_A T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:33:16.0000000' AS DateTime2), NULL, CAST(N'2019-11-06T21:33:41.0000000' AS DateTime2), 0, 0, 1, NULL)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'MP_MASTER', N'safran', N'safran_staging', N'MP_MASTER', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.MP_MASTER T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:30:50.0000000' AS DateTime2), CAST(N'2019-11-06T21:31:25.0000000' AS DateTime2), CAST(N'2019-11-01T17:41:01.0000000' AS DateTime2), 9, 20, 1, 681368834)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'MP_MEMBER', N'safran', N'safran_staging', N'MP_MEMBER', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.MP_MEMBER T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:31:31.0000000' AS DateTime2), CAST(N'2019-11-06T21:31:58.0000000' AS DateTime2), CAST(N'2019-11-01T17:41:16.0000000' AS DateTime2), 204, 221, 1, 684310119)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'MSP_UFIELD_MAPPING', N'safran', N'safran_staging', N'MSP_UFIELD_MAPPING', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.MSP_UFIELD_MAPPING T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:32:31.0000000' AS DateTime2), CAST(N'2019-11-06T21:32:57.0000000' AS DateTime2), CAST(N'2019-11-01T17:46:06.0000000' AS DateTime2), 150, 450, 1, 147120701)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'NETWORKS', N'safran', N'safran_staging', N'NETWORKS', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.NETWORKS T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:34:07.0000000' AS DateTime2), CAST(N'2019-11-06T21:34:45.0000000' AS DateTime2), CAST(N'2019-11-01T18:12:56.0000000' AS DateTime2), 255, 666, 1, 684827081)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'OUTLINE_CODES', N'safran', N'safran_staging', N'OUTLINE_CODES', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.OUTLINE_CODES T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:32:05.0000000' AS DateTime2), CAST(N'2019-11-06T21:32:33.0000000' AS DateTime2), CAST(N'2019-11-01T17:43:06.0000000' AS DateTime2), 1205538, 3193343, 1, 684621068)
GO
INSERT [Any2Omnia].[Jobs_Datasets] ([JobName], [SourceSchema], [SourceTableOrView], [DestinationSchema], [DestinationStagingSchema], [DestinationTable], [ExtractionSQL], [HighWaterColumn], [FilenameTemplate], [Enabled], [FullCopyOnNextRun], [SortOrder], [HighWaterMark], [ExtractionTimeUTC], [LastSuccessfulDelta], [LastSuccessfulFull], [RowCountSource], [RowCountSink], [HighWaterMarkSCN], [HighWaterMarkNumber]) VALUES (N'Safran-p300-MMP', N'SAFRANSA', N'RESOURCES', N'safran', N'safran_staging', N'RESOURCES', N'select ora_rowscn meta_OraRowScn, {{SourceDatabase}} META_SourceDatabase, T.* from SAFRANSA.RESOURCES T', N'meta_OraRowScn', N'%SourceTableOrView%_%YY%_%MM%_%DD%_%hh%_%mm%_%ss%_%RunMode%.parquet', 1, 0, NULL, NULL, CAST(N'2019-11-06T21:32:40.0000000' AS DateTime2), CAST(N'2019-11-06T21:33:10.0000000' AS DateTime2), CAST(N'2019-11-01T17:45:27.0000000' AS DateTime2), 1143297, 3363713, 1, 684829161)
GO
